export const routes = {
  onboarding: "/onboarding",
  login: "/(auth)/login",
  register: "/(auth)/register",
  tabs: "/(protected)/(tabs)",
  home: "/(protected)/(tabs)",
  inventory: "/(protected)/(tabs)/inventory",
  schedule: "/(protected)/(tabs)/schedule",
  store: "/(protected)/(tabs)/store",
  settings: "/(protected)/(tabs)/settings",
  chat: "/(protected)/chat",
  wearables: "/(protected)/wearables",
  profile: "/(protected)/profile",
  profileSetup: "/(protected)/profile-setup",
  notifications: "/(protected)/notifications",
  privacy: "/(protected)/privacy",
  addDevice: "/(protected)/add-device",
  deviceSelection: "/(protected)/device-selection",
  deviceSetup: "/(protected)/device-setup",
  support: "/(protected)/support"
};
